-- DB2 Schema for Dual-Mode System
-- Supports both Attendance Reports and Mainframe Assignment

-- ===== ATTENDANCE MODE TABLES =====

-- Drop table if exists (for clean restart)
DROP TABLE IF EXISTS EMPLOYEE_ATTENDANCE;

-- Create table for employee attendance records
CREATE TABLE EMPLOYEE_ATTENDANCE (
    ATTENDANCE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMP_ID VARCHAR(20) NOT NULL,
    EMP_NAME VARCHAR(100) NOT NULL,
    ATTENDANCE_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CHECK_IN_TIME TIME,
    CHECK_OUT_TIME TIME,
    UPLOAD_BATCH VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for attendance
CREATE INDEX IDX_EMP_ID ON EMPLOYEE_ATTENDANCE(EMP_ID);
CREATE INDEX IDX_ATTENDANCE_DATE ON EMPLOYEE_ATTENDANCE(ATTENDANCE_DATE);
CREATE INDEX IDX_ATT_BATCH ON EMPLOYEE_ATTENDANCE(UPLOAD_BATCH);

-- ===== ASSIGNMENT MODE TABLES =====

-- Drop table if exists (for clean restart)
DROP TABLE IF EXISTS ASSIGNMENT_RECORDS;

-- Create main table for sorted PS file records
CREATE TABLE ASSIGNMENT_RECORDS (
    RECORD_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRIMARY_KEY VARCHAR(8) NOT NULL,
    COLUMNS_1_12 VARCHAR(12),
    COLUMNS_21_80 VARCHAR(60),
    FULL_RECORD VARCHAR(80) NOT NULL,
    UPLOAD_BATCH VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on primary key for faster lookups
CREATE INDEX IDX_PRIMARY_KEY ON ASSIGNMENT_RECORDS(PRIMARY_KEY);

-- Create index on upload batch for filtering
CREATE INDEX IDX_ASSIGNMENT_BATCH ON ASSIGNMENT_RECORDS(UPLOAD_BATCH);

-- ===== SHARED STATISTICS TABLE =====

-- Table to track upload statistics (for both modes)
CREATE TABLE UPLOAD_STATS (
    STAT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID VARCHAR(50) NOT NULL,
    MODE VARCHAR(20) NOT NULL,
    TOTAL_RECORDS INTEGER,
    DUPLICATES_REMOVED INTEGER,
    UNIQUE_RECORDS INTEGER,
    JOB_STATUS VARCHAR(20),
    RETURN_CODE INTEGER,
    UPLOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on mode for filtering
CREATE INDEX IDX_MODE ON UPLOAD_STATS(MODE);

-- Comments
COMMENT ON TABLE EMPLOYEE_ATTENDANCE IS 'Stores employee attendance records';
COMMENT ON TABLE ASSIGNMENT_RECORDS IS 'Stores processed PS file records after duplicate removal and sorting';
COMMENT ON TABLE UPLOAD_STATS IS 'Tracks processing statistics for both attendance and assignment modes';
