-- DDL: Create JOBS and SPOOL_LINES tables for mainframe job queue + spool simulation
-- Run using the DB2 CLP (example below). Adjust schema/user/password as needed.

-- Optional: set schema
-- SET CURRENT SCHEMA = YOUR_SCHEMA_NAME;

CREATE TABLE IF NOT EXISTS JOBS (
  JOB_ID VARCHAR(50) NOT NULL PRIMARY KEY,
  JOB_NAME VARCHAR(128),
  SUBMITTED_BY VARCHAR(100),
  SUBMIT_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'INPUT',
  RETURN_CODE INTEGER DEFAULT 0,
  JCL CLOB,
  UPDATED_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

CREATE INDEX IDX_JOBS_STATUS ON JOBS(STATUS);

CREATE TABLE IF NOT EXISTS SPOOL_LINES (
  SPOOL_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
  JOB_ID VARCHAR(50) NOT NULL,
  LINE_NO INTEGER NOT NULL,
  LINE_TEXT VARCHAR(1024),
  CONSTRAINT FK_SPOOL_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);

-- Optional: grant privileges to the application user
-- GRANT SELECT, INSERT, UPDATE, DELETE ON JOBS TO db2inst1;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON SPOOL_LINES TO db2inst1;

-- Commit changes
COMMIT;
