-- DDL for DB2 - JOBS and SPOOL_LINES
CREATE TABLE JOBS (
  JOB_ID VARCHAR(50) NOT NULL PRIMARY KEY,
  JOB_NAME VARCHAR(100),
  SUBMITTED_BY VARCHAR(100),
  SUBMIT_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  STATUS VARCHAR(20),
  RETURN_CODE INTEGER DEFAULT 0,
  JCL CLOB,
  UPDATED_TS TIMESTAMP
);

CREATE TABLE SPOOL_LINES (
  SPOOL_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  JOB_ID VARCHAR(50) NOT NULL,
  LINE_NO INTEGER NOT NULL,
  LINE_TEXT VARCHAR(1024),
  CONSTRAINT FK_SPOOL_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);

CREATE INDEX IDX_JOBS_STATUS ON JOBS (STATUS);
CREATE INDEX IDX_SPOOL_JOBID ON SPOOL_LINES (JOB_ID);

COMMIT;
